"""
Jailbreak Detector using one-vs-rest SVMs
generates embeddings with SentenceTransformer "MongoDB/mdbr-leaf-ir".
Edu embeddings are stored in a separate folder (EMBEDDINGS_DATA_DIR)
"""

import os
import json
import pickle
import random
import logging
from pathlib import Path
from typing import List, Dict, Optional

import numpy as np
from dotenv import load_dotenv
load_dotenv()

from sentence_transformers import SentenceTransformer
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from tqdm import tqdm

# config

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)


ARTIFACTS_DIR = Path(os.getenv("ARTIFACTS_DIR", "artifacts"))
INDEX_PATH     = ARTIFACTS_DIR / "topic_index.json"
SVM_DIR        = ARTIFACTS_DIR / "atk_svm_models"            # will hold jailbreak models
JAILBREAK_DIR  = ARTIFACTS_DIR / "jailbreak"                 # embeddings & metadata

ARTIFACTS_DIR.mkdir(parents=True, exist_ok=True)
SVM_DIR.mkdir(parents=True, exist_ok=True)
JAILBREAK_DIR.mkdir(parents=True, exist_ok=True)

LOCAL_DATA_DIR = Path(os.getenv("LOCAL_DATA_DIR", "../../offtopic_experiments/local_data/"))   
# where educational data lives

# where to store/load the new embeddings for educational data
EMBEDDINGS_DATA_DIR = Path(os.getenv("EMBEDDINGS_DATA_DIR", "local_data_mdbr"))

EMBEDDINGS_DATA_DIR.mkdir(parents=True, exist_ok=True)

# SVM hyperparameters
SVM_KERNEL = "rbf"
SVM_C = 1.0
SVM_GAMMA = "scale"
RANDOM_SEED = 42

# SentenceTransformer model (lazy loading to prevent loading multiple times)

_model = None

def get_model():
    global _model
    if _model is None:
        log.info("Loading SentenceTransformer model: MongoDB/mdbr-leaf-ir")
        _model = SentenceTransformer("MongoDB/mdbr-leaf-ir")
    return _model

def get_embedding(text: str) -> np.ndarray:
    # return embedding for a single text
    model = get_model()
    return model.encode(text, convert_to_numpy=True)

# edu data helpers

def load_topic_index() -> dict:
    # load the topic index generated by download_per_topic.py
    if not INDEX_PATH.exists():
        raise FileNotFoundError(f"Topic index not found at {INDEX_PATH}. Run original build first.")
    with open(INDEX_PATH, "r") as f:
        return json.load(f)

def get_topic_embeddings_path(topic_id: str) -> Path:
    # return path where the embeddings for this topic should be stored
    return EMBEDDINGS_DATA_DIR / topic_id / "questions_embeddings.npy"

def load_full_question_embeddings(topic_id: str) -> np.ndarray:
    # load the embeddings array for an educational topic from the folder
    emb_file = get_topic_embeddings_path(topic_id)
    if not emb_file.exists():
        raise FileNotFoundError(
            f"Embeddings not found at {emb_file}. "
            "Please run --generate-edu-embeddings first."
        )
    return np.load(emb_file)

def load_question_texts(topic_id: str) -> List[str]:
    # load the original question texts from LOCAL_DATA_DIR
    # this is used for analysis to check where the model fails
    q_file = LOCAL_DATA_DIR / topic_id / "questions.json"
    if not q_file.exists():
        return []
    with open(q_file, "r") as f:
        return json.load(f)

# generate edu embeddings

def generate_educational_embeddings():
    # generate embeddings for all topics listed in topic_index.json using MDBR-leaf-ir model
    topic_index = load_topic_index()
    log.info(f"Generating embeddings for {len(topic_index)} topics...")

    for topic_name, info in tqdm(topic_index.items(), desc="Topics"):
        topic_id = info["topic_id"]
        texts = load_question_texts(topic_id)
        if not texts:
            log.warning(f"No questions found for {topic_name} ({topic_id}), skipping.")
            continue

        # embed in batches to avoid memory issues (doesn't slow things down much)
        model = get_model()
        embeddings = model.encode(texts, convert_to_numpy=True, show_progress_bar=False)

        # save to new folder
        out_dir = EMBEDDINGS_DATA_DIR / topic_id
        out_dir.mkdir(parents=True, exist_ok=True)
        np.save(out_dir / "questions_embeddings.npy", embeddings)
        log.debug(f"Saved {len(embeddings)} embeddings for {topic_name}")

    log.info("Educational embedding generation complete.")

# jailbreak data preparation (using the same MDBR-leaf-ir)

def prepare_jailbreak_data(json_paths: List[Path]):
    # load jailbreak patterns from JSON files, create embeddings
    all_patterns = []
    for path in json_paths:
        with open(path, "r") as f:
            data = json.load(f)
        patterns = data.get("patterns", [])
        log.info(f"Loaded {len(patterns)} patterns from {path}")
        all_patterns.extend(patterns)

    log.info(f"Total patterns before filtering: {len(all_patterns)}")

    # required keys: id, attack_class, pattern 
    # (bypass_technique is optional, only tagged for a few dozen examples)
    required_keys = {"id", "attack_class", "pattern"}
    valid_patterns = []
    for p in all_patterns:
        if required_keys.issubset(p.keys()):
            valid_patterns.append(p)
        else:
            missing = required_keys - p.keys()
            log.warning(f"Skipping pattern (ID: {p.get('id', 'unknown')}) missing keys: {missing}")

    if not valid_patterns:
        raise ValueError("No valid patterns remain after filtering. Check your JSON files")

    log.info(f"Valid patterns to process: {len(valid_patterns)}")

    model = get_model()
    texts = [p["pattern"] for p in valid_patterns]
    log.info("Computing jailbreak embeddings...")
    emb_array = model.encode(texts, convert_to_numpy=True, show_progress_bar=True)

    metadata = []
    for p, emb in zip(valid_patterns, emb_array):
        # use .get() to default to None if bypass_technique is missing
        metadata.append({
            "id": p["id"],
            "attack_class": p["attack_class"],
            "bypass_technique": p.get("bypass_technique"),  # becomes None if absent
            "pattern": p["pattern"]
        })

    np.save(JAILBREAK_DIR / "embeddings.npy", emb_array)
    with open(JAILBREAK_DIR / "metadata.json", "w") as f:
        json.dump(metadata, f, indent=2)

    # build category indices, excluding null bypass_technique from its index
    attack_to_idx = {}
    bypass_to_idx = {}
    for i, m in enumerate(metadata):
        attack_to_idx.setdefault(m["attack_class"], []).append(i)
        if m["bypass_technique"] is not None:
            bypass_to_idx.setdefault(m["bypass_technique"], []).append(i)

    with open(JAILBREAK_DIR / "attack_index.json", "w") as f:
        json.dump(attack_to_idx, f)
    with open(JAILBREAK_DIR / "bypass_index.json", "w") as f:
        json.dump(bypass_to_idx, f)

    log.info(f"Prepared {len(metadata)} jailbreak embeddings.")

# sample genuine negatives (from the edu embeddings folder)

def sample_genuine_embeddings(topic_index: dict, n_samples: int = 200000) -> np.ndarray:
    # randomly sample n_samples genuine embeddings from all topics
    all_genuine = []
    samples_per_topic = max(50, n_samples // len(topic_index))
    for topic_name, info in topic_index.items():
        emb = load_full_question_embeddings(info["topic_id"])
        take = min(samples_per_topic, len(emb))
        if take <= 0:
            continue
        idx = np.random.choice(len(emb), take, replace=False)
        all_genuine.append(emb[idx])

    if not all_genuine:
        raise RuntimeError("No edu embeddings could be sampled.")
    genuine = np.vstack(all_genuine)
    if len(genuine) > n_samples:
        idx = np.random.choice(len(genuine), n_samples, replace=False)
        genuine = genuine[idx]
    return genuine

# one-vs-rest training

def train_one_vs_rest(category: str,
                      category_values: List[str],
                      jailbreak_emb: np.ndarray,
                      jailbreak_meta: List[dict],
                      genuine_emb: np.ndarray,
                      include_other_jailbreaks: bool = True):
    # train binary SVM for each category value
    # we build a multi-class classifier using several binary classifiers
    # ideally, do not use intra-class jailbreaks as negatives to improve accuracy
    # the jailbreak type classification will be worse, but overall accuracy should improve
    # have added option to enable or disable using arg to the script
    for cat_val in tqdm(category_values, desc=f"Training {category} classifiers"):
        pos_idx = [i for i, m in enumerate(jailbreak_meta) if m[category] == cat_val]
        pos_emb = jailbreak_emb[pos_idx]

        if len(pos_emb) == 0:
            log.warning(f"No examples for {category} = {cat_val}, skipping.")
            continue

        neg_emb = genuine_emb.copy()

        if include_other_jailbreaks:
            other_idx = [i for i in range(len(jailbreak_meta)) if i not in pos_idx]
            if other_idx:
                other_emb = jailbreak_emb[other_idx]
                max_other = min(len(other_emb), len(pos_emb) * 2)
                if max_other < len(other_emb):
                    samp = np.random.choice(len(other_emb), max_other, replace=False)
                    other_emb = other_emb[samp]
                neg_emb = np.vstack([neg_emb, other_emb])

        X = np.vstack([pos_emb, neg_emb])
        y = np.array([1] * len(pos_emb) + [0] * len(neg_emb))

        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)

        svm = SVC(kernel=SVM_KERNEL, C=SVM_C, gamma=SVM_GAMMA,
                  probability=True, random_state=RANDOM_SEED)
        svm.fit(X_scaled, y)

        model_data = {"scaler": scaler, "svm": svm}
        safe_name = cat_val.replace(" ", "_").replace("/", "_")
        model_path = SVM_DIR / f"jailbreak_{category}_{safe_name}.pkl"
        with open(model_path, "wb") as f:
            pickle.dump(model_data, f)

        log.info(f"Trained {category} '{cat_val}': {len(pos_emb)} positives, {len(neg_emb)} negatives")

# JailbreakDetector class 
# converts numpy types to Python natives to speed up the code

class JailbreakDetector:
    def __init__(self, threshold: float = 0.5):
        self.threshold = threshold
        self.attack_models = self._load_models("attack_class")
        self.bypass_models = self._load_models("bypass_technique")

    # __ for fancy OOPS
    def _load_models(self, category: str) -> Dict[str, dict]:
        models = {}
        pattern = f"jailbreak_{category}_*.pkl"
        for path in SVM_DIR.glob(pattern):
            stem = path.stem
            prefix = f"jailbreak_{category}_"
            if not stem.startswith(prefix):
                continue
            class_val = stem[len(prefix):]
            with open(path, "rb") as f:
                models[class_val] = pickle.load(f)
        log.info(f"Loaded {len(models)} {category} models.")
        return models

    def predict(self, embedding: np.ndarray) -> dict:
        attack_probs = {}
        for cls, model in self.attack_models.items():
            emb_scaled = model["scaler"].transform(embedding.reshape(1, -1))
            prob = model["svm"].predict_proba(emb_scaled)[0][1]
            # convert numpy float to Python float
            attack_probs[cls] = float(prob)  

        bypass_probs = {}
        for cls, model in self.bypass_models.items():
            emb_scaled = model["scaler"].transform(embedding.reshape(1, -1))
            prob = model["svm"].predict_proba(emb_scaled)[0][1]
            bypass_probs[cls] = float(prob)

        max_attack = max(attack_probs.values()) if attack_probs else 0.0
        max_bypass = max(bypass_probs.values()) if bypass_probs else 0.0
        # convert numpy bool to Python bool
        is_jailbreak = bool(max(max_attack, max_bypass) >= self.threshold)

        pred_attack = max(attack_probs, key=attack_probs.get) if attack_probs else None
        pred_bypass = max(bypass_probs, key=bypass_probs.get) if bypass_probs else None

        return {
            "is_jailbreak": is_jailbreak,
            "attack_class": pred_attack if is_jailbreak else None,
            "attack_class_probabilities": attack_probs,
            "bypass_technique": pred_bypass if is_jailbreak else None,
            "bypass_technique_probabilities": bypass_probs,
        }

# added a bunch of arg options to make iteration easier
# have now implemented --no-other-jailbreaks for negatives
# implemented --classify for some basic sanity checks

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Jailbreak Detector")
    parser.add_argument("--generate-edu-embeddings", action="store_true",
                        help="Generate embeddings for all edu topics using SentenceTransformer")
    parser.add_argument("--prepare", type=str, nargs='+',
                        help="Path(s) to jailbreak JSON file(s) to prepare embeddings")
    parser.add_argument("--train", action="store_true", help="Train all one-vs-rest classifiers")
    parser.add_argument("--classify", type=str, help="Classify a single text")
    parser.add_argument("--threshold", type=float, default=0.5, help="confidence threshold")
    parser.add_argument("--genuine-samples", type=int, default=20000, help="Number of genuine negatives")
    parser.add_argument("--no-other-jailbreaks", action="store_true",
                        help="Do not include other jailbreaks as negatives")
    args = parser.parse_args()

    if args.generate_edu_embeddings:
        generate_educational_embeddings()

    if args.prepare:
        prepare_jailbreak_data([Path(p) for p in args.prepare])

    if args.train:
        # load jailbreak data
        jailbreak_emb = np.load(JAILBREAK_DIR / "embeddings.npy")
        with open(JAILBREAK_DIR / "metadata.json", "r") as f:
            jailbreak_meta = json.load(f)

        # load topic index and sample genuine negatives
        topic_index = load_topic_index()
        log.info("Sampling genuine embeddings...")
        genuine_emb = sample_genuine_embeddings(topic_index, n_samples=args.genuine_samples)

        # get unique jailbreak categories 
        # exclude None from bypass techniques
        attack_values = list(set(m["attack_class"] for m in jailbreak_meta))
        bypass_values = list(set(
            m["bypass_technique"] for m in jailbreak_meta if m["bypass_technique"] is not None
        ))
        log.info(f"Attack classes: {attack_values}")
        log.info(f"Bypass techniques: {bypass_values}")

        # train classifiers
        train_one_vs_rest("attack_class", attack_values, jailbreak_emb, jailbreak_meta,
                          genuine_emb, include_other_jailbreaks=not args.no_other_jailbreaks)
        train_one_vs_rest("bypass_technique", bypass_values, jailbreak_emb, jailbreak_meta,
                          genuine_emb, include_other_jailbreaks=not args.no_other_jailbreaks)

        log.info("All training completed.")

    if args.classify:
        detector = JailbreakDetector(threshold=args.threshold)
        emb = get_embedding(args.classify)
        result = detector.predict(emb)
        print(json.dumps(result, indent=2))